### ISSUE TITLE
Handle .pls files

### ISSUE THREAD

**Issue by rdebeasi** [segler-alex/radiobrowser-api#19] opened 2017-02-01 21:08 UTC
Is the API able to handle .pls files correctly?

I ask because all of the SomaFM stations are currently showing up as broken. These stations have .pls files listed for their URLs. Other stations in the database use .m3u or .mp3 files as their URLs.

If only specific file formats are supported, it might be useful to add that information to the docs. Or, if the file format is ok but there's something weird about the stations themselves, I'd appreciate any thoughts on the right way to troubleshoot.

RadioBrowser rocks - thanks for making it! :smile:

--- 

Edit: [This station](http://www.radio-browser.info/gui/#/edit/86408) has a .pls file and works properly, so maybe it's not the file format after all. Any thoughts on why the stations are showing up as broken?

**Comment by segler-alex** [comment] 2017-02-01 21:18
duplicate of
https://github.com/segler-alex/RadioDroid/issues/109

**Closed by segler-alex** 2017-02-01 21:18 UTC
